[2023-01-25 23:21:48,199] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Respuesta_Nasa.Notificar_Analistas scheduled__2023-01-02T00:00:00+00:00 [queued]>
[2023-01-25 23:21:48,215] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Respuesta_Nasa.Notificar_Analistas scheduled__2023-01-02T00:00:00+00:00 [queued]>
[2023-01-25 23:21:48,215] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-01-25 23:21:48,215] {taskinstance.py:1377} INFO - Starting attempt 1 of 3
[2023-01-25 23:21:48,215] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-01-25 23:21:48,231] {taskinstance.py:1397} INFO - Executing <Task(EmailOperator): Notificar_Analistas> on 2023-01-02 00:00:00+00:00
[2023-01-25 23:21:48,237] {standard_task_runner.py:52} INFO - Started process 3899 to run task
[2023-01-25 23:21:48,240] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Respuesta_Nasa', 'Notificar_Analistas', 'scheduled__2023-01-02T00:00:00+00:00', '--job-id', '494', '--raw', '--subdir', 'DAGS_FOLDER/00-ETL_spaceX.py', '--cfg-path', '/tmp/tmpdsa8wu9f', '--error-file', '/tmp/tmpuq9n9odo']
[2023-01-25 23:21:48,241] {standard_task_runner.py:80} INFO - Job 494: Subtask Notificar_Analistas
[2023-01-25 23:21:48,329] {task_command.py:371} INFO - Running <TaskInstance: Respuesta_Nasa.Notificar_Analistas scheduled__2023-01-02T00:00:00+00:00 [running]> on host fd9891b969b0
[2023-01-25 23:21:48,442] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=Respuesta_Nasa
AIRFLOW_CTX_TASK_ID=Notificar_Analistas
AIRFLOW_CTX_EXECUTION_DATE=2023-01-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-02T00:00:00+00:00
[2023-01-25 23:21:48,456] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/email.py:119: PendingDeprecationWarning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2023-01-25 23:21:48,456] {configuration.py:552} WARNING - section/key [smtp/smtp_user] not found in config
[2023-01-25 23:21:48,456] {email.py:228} INFO - Email alerting: attempt 1
[2023-01-25 23:21:48,458] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/email.py", line 85, in execute
    custom_headers=self.custom_headers,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 71, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 119, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 230, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 264, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2023-01-25 23:21:48,469] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=Respuesta_Nasa, task_id=Notificar_Analistas, execution_date=20230102T000000, start_date=20230125T232148, end_date=20230125T232148
[2023-01-25 23:21:48,486] {standard_task_runner.py:97} ERROR - Failed to execute job 494 for task Notificar_Analistas ([Errno 99] Cannot assign requested address; 3899)
[2023-01-25 23:21:48,532] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-01-25 23:21:48,574] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
