[2023-01-25 23:23:51,598] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Respuesta_Nasa.Notificar_Analistas scheduled__2023-01-02T00:00:00+00:00 [queued]>
[2023-01-25 23:23:51,612] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Respuesta_Nasa.Notificar_Analistas scheduled__2023-01-02T00:00:00+00:00 [queued]>
[2023-01-25 23:23:51,612] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-01-25 23:23:51,612] {taskinstance.py:1377} INFO - Starting attempt 3 of 3
[2023-01-25 23:23:51,613] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-01-25 23:23:51,631] {taskinstance.py:1397} INFO - Executing <Task(EmailOperator): Notificar_Analistas> on 2023-01-02 00:00:00+00:00
[2023-01-25 23:23:51,637] {standard_task_runner.py:52} INFO - Started process 4017 to run task
[2023-01-25 23:23:51,645] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Respuesta_Nasa', 'Notificar_Analistas', 'scheduled__2023-01-02T00:00:00+00:00', '--job-id', '501', '--raw', '--subdir', 'DAGS_FOLDER/00-ETL_spaceX.py', '--cfg-path', '/tmp/tmp2_39ms1w', '--error-file', '/tmp/tmpgn9b7uju']
[2023-01-25 23:23:51,647] {standard_task_runner.py:80} INFO - Job 501: Subtask Notificar_Analistas
[2023-01-25 23:23:51,738] {task_command.py:371} INFO - Running <TaskInstance: Respuesta_Nasa.Notificar_Analistas scheduled__2023-01-02T00:00:00+00:00 [running]> on host fd9891b969b0
[2023-01-25 23:23:51,839] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=Respuesta_Nasa
AIRFLOW_CTX_TASK_ID=Notificar_Analistas
AIRFLOW_CTX_EXECUTION_DATE=2023-01-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-02T00:00:00+00:00
[2023-01-25 23:23:51,853] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/email.py:119: PendingDeprecationWarning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2023-01-25 23:23:51,853] {configuration.py:552} WARNING - section/key [smtp/smtp_user] not found in config
[2023-01-25 23:23:51,853] {email.py:228} INFO - Email alerting: attempt 1
[2023-01-25 23:23:51,854] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/email.py", line 85, in execute
    custom_headers=self.custom_headers,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 71, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 119, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 230, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 264, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2023-01-25 23:23:51,865] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=Respuesta_Nasa, task_id=Notificar_Analistas, execution_date=20230102T000000, start_date=20230125T232351, end_date=20230125T232351
[2023-01-25 23:23:51,883] {standard_task_runner.py:97} ERROR - Failed to execute job 501 for task Notificar_Analistas ([Errno 99] Cannot assign requested address; 4017)
[2023-01-25 23:23:51,895] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-01-25 23:23:51,937] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
