[2023-01-26 16:41:44,942] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Respuesta_Nasa.send_email_notification scheduled__2023-01-03T00:00:00+00:00 [queued]>
[2023-01-26 16:41:44,958] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Respuesta_Nasa.send_email_notification scheduled__2023-01-03T00:00:00+00:00 [queued]>
[2023-01-26 16:41:44,958] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-01-26 16:41:44,958] {taskinstance.py:1377} INFO - Starting attempt 6 of 6
[2023-01-26 16:41:44,959] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-01-26 16:41:44,976] {taskinstance.py:1397} INFO - Executing <Task(EmailOperator): send_email_notification> on 2023-01-03 00:00:00+00:00
[2023-01-26 16:41:44,981] {standard_task_runner.py:52} INFO - Started process 463 to run task
[2023-01-26 16:41:44,986] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Respuesta_Nasa', 'send_email_notification', 'scheduled__2023-01-03T00:00:00+00:00', '--job-id', '560', '--raw', '--subdir', 'DAGS_FOLDER/00-ETL_spaceX.py', '--cfg-path', '/tmp/tmplecz30jj', '--error-file', '/tmp/tmp9bb27ky1']
[2023-01-26 16:41:44,988] {standard_task_runner.py:80} INFO - Job 560: Subtask send_email_notification
[2023-01-26 16:41:45,082] {task_command.py:371} INFO - Running <TaskInstance: Respuesta_Nasa.send_email_notification scheduled__2023-01-03T00:00:00+00:00 [running]> on host 1e10284898e4
[2023-01-26 16:41:45,166] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=Respuesta_Nasa
AIRFLOW_CTX_TASK_ID=send_email_notification
AIRFLOW_CTX_EXECUTION_DATE=2023-01-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=6
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-03T00:00:00+00:00
[2023-01-26 16:41:45,177] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/email.py:119: PendingDeprecationWarning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2023-01-26 16:41:45,178] {email.py:228} INFO - Email alerting: attempt 1
[2023-01-26 16:41:46,152] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/email.py", line 85, in execute
    custom_headers=self.custom_headers,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 71, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 119, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 239, in send_mime_email
    smtp_conn.login(smtp_user, smtp_password)
  File "/usr/local/lib/python3.7/smtplib.py", line 735, in login
    raise last_exception
  File "/usr/local/lib/python3.7/smtplib.py", line 726, in login
    initial_response_ok=initial_response_ok)
  File "/usr/local/lib/python3.7/smtplib.py", line 647, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (534, b'5.7.9 Application-specific password required. Learn more at\n5.7.9  https://support.google.com/mail/?p=InvalidSecondFactor bq16-20020a05622a1c1000b003b7fcbbb020sm970165qtb.81 - gsmtp')
[2023-01-26 16:41:46,161] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=Respuesta_Nasa, task_id=send_email_notification, execution_date=20230103T000000, start_date=20230126T164144, end_date=20230126T164146
[2023-01-26 16:41:46,176] {standard_task_runner.py:97} ERROR - Failed to execute job 560 for task send_email_notification ((534, b'5.7.9 Application-specific password required. Learn more at\n5.7.9  https://support.google.com/mail/?p=InvalidSecondFactor bq16-20020a05622a1c1000b003b7fcbbb020sm970165qtb.81 - gsmtp'); 463)
[2023-01-26 16:41:46,202] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-01-26 16:41:46,251] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
